### ISSUE TITLE
Blacklist in options tab

### ISSUE THREAD

**Issue by SpiritBuddy** [necromancyonline/necromancy-server#70]
black list in options window takes me back to the login screen with a message that I've been disconnected from the server.

**To Reproduce**
1. enter game
2. navigate to options window
3. click black list

**Comment by WizOnHiraeth** [comment]
Temp Fix on my small fixes branch. Unk is working on getting the database fixed for this and will hopefully be working soon

**Comment by Unknownone69** [comment]
This was fixed for the U.S. client. It works on Jp client. Closing.
