### ISSUE TITLE
Line moved to new line by accident?

### ISSUE THREAD

**Issue by RavaRavn** [necromancyonline/necromancy-server#78]
It got brought down to a new line accidentally? How would I suggest changes? I've seen a lot of things like this. Including translations.

https://github.com/necromancyonline/necromancy-server/blob/ebdc38bfc77ba4aa504fb172ee476770c27ea09d/Necromancy.Server/Chat/Command/Commands/ItemCommand.cs#L337

**Comment by WizOnHiraeth** [comment]
Is this causing the code to break, or not work properly?

**Comment by WizOnHiraeth** [comment]
Issue has been fixed in most recent push :)

**Comment by WizOnHiraeth** [comment]
we will fix in next push >.>

**Comment by RavaRavn** [comment]
...

**Comment by WizOnHiraeth** [comment]
dont ... me >.>

**Comment by RavaRavn** [comment]
then don't >.> me

**Comment by sebastian-heinz** [comment]
the editor has a maximum line length, if that is exceeded it will break to next line. This can often happen with long comments. This one however does not seem to long. I don't think we need to raise any issues for these type of unpleasent formatting - for now. This has no effect on code execution and is purley visual offending. Additionally there are alot of commands for testing so the command code in general is quite messy. I think at some point we should delete most of the unessary commands that only perform a single send for testing once understood and only keep commands that are actually usefull for in game mechanics (spawning [item; monster; npc], teleporting, map change, etc) - Thank you for raising this concern but I don't think this should be our focus at the moment as there are more critical parts to be dealt with :)
