### ISSUE TITLE
Screen Resolution

### ISSUE THREAD

**Issue by riveran21** [necromancyonline/necromancy-server#89]
**Describe the bug**
When I try to switch the game resolution from the default to 1920x1080 it distorts all of the views, such that images are of the screen and off-center.

**To Reproduce**
1. Log in to game.
2. Click 'o' to go to settings.
3. Set video resolution to 1920x1080
4. Save Settings
5. Close game and re-start.

**Expected behavior**
All of the graphics, input boxes and videos are appropriately centered and sized for the larger resolution.

**Screenshots**
![image](https://user-images.githubusercontent.com/57384641/82614059-865a1a00-9b8c-11ea-9ed8-b829c7c5b0a2.png)

**Additional context**

**Comment by FoolsZenith** [comment]
It's not a problem with the game but rather with your DPI scaling. Right click "WizardryOnline_patched.exe" and go to properties. Once you're there, go to the compatibility tab and click "Change high DPI settings". Once you're there, tick "override high DPI scaling behaivour". This should fix your problem.

**Comment by riveran21** [comment]
@FoolsZenith - This fixed the issue. I see what happened here. I have windows DPI set to 125% (I'm getting old) and that's affecting the resolution in the game. This may have fixed a problem I was having with the resolution for another old game too. Thanks for the info!
