### ISSUE TITLE
Re-Roll Bonus Button

### ISSUE THREAD

**Issue by riveran21** [necromancyonline/necromancy-server#93]
**Please describe the idea.**
A "re-roll" button during character creation that simply re-rolls the number of bonus points.

**Describe the solution you'd like**
During Character Creation, when the initial bonus points is displayed add a "re-roll" button that allows you to simply roll a new bonus. Currently you have to accept the bonus points, cancel your character creation and start over from the race selection screen.

In the Japan version of the game they eventually added this new functionality making it much easier and less monotonous to re-roll for higher bonus points.

**Describe alternatives you've considered**

**Additional context**

**Comment by Unknownone69** [comment]
The button exists on the Jp client which we will be moving to soon so I will close this.
